export default (app) => {
  app.post(
    `/tenant/:tenantId/user`,
    require('./userCreate').default,
  );
  app.put(
    `/tenant/:tenantId/user`,
    require('./userEdit').default,
  );
  app.delete(
    `/tenant/:tenantId/user`,
    require('./userDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/user`,
    require('./userList').default,
  );
  app.get(
    `/tenant/:tenantId/user/:id`,
    require('./userFind').default,
  );
};
